// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/bootstrap/v3alpha/bootstrap.proto

package envoy_config_bootstrap_v3alpha

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	v3alpha4 "github.com/envoyproxy/go-control-plane/envoy/api/v3alpha"
	auth "github.com/envoyproxy/go-control-plane/envoy/api/v3alpha/auth"
	core "github.com/envoyproxy/go-control-plane/envoy/api/v3alpha/core"
	v3alpha "github.com/envoyproxy/go-control-plane/envoy/config/metrics/v3alpha"
	v3alpha2 "github.com/envoyproxy/go-control-plane/envoy/config/overload/v3alpha"
	v3alpha1 "github.com/envoyproxy/go-control-plane/envoy/config/trace/v3alpha"
	v3alpha3 "github.com/envoyproxy/go-control-plane/envoy/config/wasm/v3alpha"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bootstrap struct {
	Node                       *core.Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	StaticResources            *Bootstrap_StaticResources  `protobuf:"bytes,2,opt,name=static_resources,json=staticResources,proto3" json:"static_resources,omitempty"`
	DynamicResources           *Bootstrap_DynamicResources `protobuf:"bytes,3,opt,name=dynamic_resources,json=dynamicResources,proto3" json:"dynamic_resources,omitempty"`
	ClusterManager             *ClusterManager             `protobuf:"bytes,4,opt,name=cluster_manager,json=clusterManager,proto3" json:"cluster_manager,omitempty"`
	HdsConfig                  *core.ApiConfigSource       `protobuf:"bytes,14,opt,name=hds_config,json=hdsConfig,proto3" json:"hds_config,omitempty"`
	FlagsPath                  string                      `protobuf:"bytes,5,opt,name=flags_path,json=flagsPath,proto3" json:"flags_path,omitempty"`
	StatsSinks                 []*v3alpha.StatsSink        `protobuf:"bytes,6,rep,name=stats_sinks,json=statsSinks,proto3" json:"stats_sinks,omitempty"`
	StatsConfig                *v3alpha.StatsConfig        `protobuf:"bytes,13,opt,name=stats_config,json=statsConfig,proto3" json:"stats_config,omitempty"`
	StatsFlushInterval         *duration.Duration          `protobuf:"bytes,7,opt,name=stats_flush_interval,json=statsFlushInterval,proto3" json:"stats_flush_interval,omitempty"`
	Watchdog                   *Watchdog                   `protobuf:"bytes,8,opt,name=watchdog,proto3" json:"watchdog,omitempty"`
	Tracing                    *v3alpha1.Tracing           `protobuf:"bytes,9,opt,name=tracing,proto3" json:"tracing,omitempty"`
	LayeredRuntime             *LayeredRuntime             `protobuf:"bytes,17,opt,name=layered_runtime,json=layeredRuntime,proto3" json:"layered_runtime,omitempty"`
	Admin                      *Admin                      `protobuf:"bytes,12,opt,name=admin,proto3" json:"admin,omitempty"`
	OverloadManager            *v3alpha2.OverloadManager   `protobuf:"bytes,15,opt,name=overload_manager,json=overloadManager,proto3" json:"overload_manager,omitempty"`
	EnableDispatcherStats      bool                        `protobuf:"varint,16,opt,name=enable_dispatcher_stats,json=enableDispatcherStats,proto3" json:"enable_dispatcher_stats,omitempty"`
	HeaderPrefix               string                      `protobuf:"bytes,18,opt,name=header_prefix,json=headerPrefix,proto3" json:"header_prefix,omitempty"`
	StatsServerVersionOverride *wrappers.UInt64Value       `protobuf:"bytes,19,opt,name=stats_server_version_override,json=statsServerVersionOverride,proto3" json:"stats_server_version_override,omitempty"`
	UseTcpForDnsLookups        bool                        `protobuf:"varint,20,opt,name=use_tcp_for_dns_lookups,json=useTcpForDnsLookups,proto3" json:"use_tcp_for_dns_lookups,omitempty"`
	WasmService                []*v3alpha3.WasmService     `protobuf:"bytes,21,rep,name=wasm_service,json=wasmService,proto3" json:"wasm_service,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *Bootstrap) Reset()         { *m = Bootstrap{} }
func (m *Bootstrap) String() string { return proto.CompactTextString(m) }
func (*Bootstrap) ProtoMessage()    {}
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{0}
}

func (m *Bootstrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bootstrap.Unmarshal(m, b)
}
func (m *Bootstrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bootstrap.Marshal(b, m, deterministic)
}
func (m *Bootstrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bootstrap.Merge(m, src)
}
func (m *Bootstrap) XXX_Size() int {
	return xxx_messageInfo_Bootstrap.Size(m)
}
func (m *Bootstrap) XXX_DiscardUnknown() {
	xxx_messageInfo_Bootstrap.DiscardUnknown(m)
}

var xxx_messageInfo_Bootstrap proto.InternalMessageInfo

func (m *Bootstrap) GetNode() *core.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Bootstrap) GetStaticResources() *Bootstrap_StaticResources {
	if m != nil {
		return m.StaticResources
	}
	return nil
}

func (m *Bootstrap) GetDynamicResources() *Bootstrap_DynamicResources {
	if m != nil {
		return m.DynamicResources
	}
	return nil
}

func (m *Bootstrap) GetClusterManager() *ClusterManager {
	if m != nil {
		return m.ClusterManager
	}
	return nil
}

func (m *Bootstrap) GetHdsConfig() *core.ApiConfigSource {
	if m != nil {
		return m.HdsConfig
	}
	return nil
}

func (m *Bootstrap) GetFlagsPath() string {
	if m != nil {
		return m.FlagsPath
	}
	return ""
}

func (m *Bootstrap) GetStatsSinks() []*v3alpha.StatsSink {
	if m != nil {
		return m.StatsSinks
	}
	return nil
}

func (m *Bootstrap) GetStatsConfig() *v3alpha.StatsConfig {
	if m != nil {
		return m.StatsConfig
	}
	return nil
}

func (m *Bootstrap) GetStatsFlushInterval() *duration.Duration {
	if m != nil {
		return m.StatsFlushInterval
	}
	return nil
}

func (m *Bootstrap) GetWatchdog() *Watchdog {
	if m != nil {
		return m.Watchdog
	}
	return nil
}

func (m *Bootstrap) GetTracing() *v3alpha1.Tracing {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *Bootstrap) GetLayeredRuntime() *LayeredRuntime {
	if m != nil {
		return m.LayeredRuntime
	}
	return nil
}

func (m *Bootstrap) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

func (m *Bootstrap) GetOverloadManager() *v3alpha2.OverloadManager {
	if m != nil {
		return m.OverloadManager
	}
	return nil
}

func (m *Bootstrap) GetEnableDispatcherStats() bool {
	if m != nil {
		return m.EnableDispatcherStats
	}
	return false
}

func (m *Bootstrap) GetHeaderPrefix() string {
	if m != nil {
		return m.HeaderPrefix
	}
	return ""
}

func (m *Bootstrap) GetStatsServerVersionOverride() *wrappers.UInt64Value {
	if m != nil {
		return m.StatsServerVersionOverride
	}
	return nil
}

func (m *Bootstrap) GetUseTcpForDnsLookups() bool {
	if m != nil {
		return m.UseTcpForDnsLookups
	}
	return false
}

func (m *Bootstrap) GetWasmService() []*v3alpha3.WasmService {
	if m != nil {
		return m.WasmService
	}
	return nil
}

type Bootstrap_StaticResources struct {
	Listeners            []*v3alpha4.Listener `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	Clusters             []*v3alpha4.Cluster  `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Secrets              []*auth.Secret       `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Bootstrap_StaticResources) Reset()         { *m = Bootstrap_StaticResources{} }
func (m *Bootstrap_StaticResources) String() string { return proto.CompactTextString(m) }
func (*Bootstrap_StaticResources) ProtoMessage()    {}
func (*Bootstrap_StaticResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{0, 0}
}

func (m *Bootstrap_StaticResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bootstrap_StaticResources.Unmarshal(m, b)
}
func (m *Bootstrap_StaticResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bootstrap_StaticResources.Marshal(b, m, deterministic)
}
func (m *Bootstrap_StaticResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bootstrap_StaticResources.Merge(m, src)
}
func (m *Bootstrap_StaticResources) XXX_Size() int {
	return xxx_messageInfo_Bootstrap_StaticResources.Size(m)
}
func (m *Bootstrap_StaticResources) XXX_DiscardUnknown() {
	xxx_messageInfo_Bootstrap_StaticResources.DiscardUnknown(m)
}

var xxx_messageInfo_Bootstrap_StaticResources proto.InternalMessageInfo

func (m *Bootstrap_StaticResources) GetListeners() []*v3alpha4.Listener {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (m *Bootstrap_StaticResources) GetClusters() []*v3alpha4.Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *Bootstrap_StaticResources) GetSecrets() []*auth.Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type Bootstrap_DynamicResources struct {
	LdsConfig            *core.ConfigSource    `protobuf:"bytes,1,opt,name=lds_config,json=ldsConfig,proto3" json:"lds_config,omitempty"`
	CdsConfig            *core.ConfigSource    `protobuf:"bytes,2,opt,name=cds_config,json=cdsConfig,proto3" json:"cds_config,omitempty"`
	AdsConfig            *core.ApiConfigSource `protobuf:"bytes,3,opt,name=ads_config,json=adsConfig,proto3" json:"ads_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Bootstrap_DynamicResources) Reset()         { *m = Bootstrap_DynamicResources{} }
func (m *Bootstrap_DynamicResources) String() string { return proto.CompactTextString(m) }
func (*Bootstrap_DynamicResources) ProtoMessage()    {}
func (*Bootstrap_DynamicResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{0, 1}
}

func (m *Bootstrap_DynamicResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bootstrap_DynamicResources.Unmarshal(m, b)
}
func (m *Bootstrap_DynamicResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bootstrap_DynamicResources.Marshal(b, m, deterministic)
}
func (m *Bootstrap_DynamicResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bootstrap_DynamicResources.Merge(m, src)
}
func (m *Bootstrap_DynamicResources) XXX_Size() int {
	return xxx_messageInfo_Bootstrap_DynamicResources.Size(m)
}
func (m *Bootstrap_DynamicResources) XXX_DiscardUnknown() {
	xxx_messageInfo_Bootstrap_DynamicResources.DiscardUnknown(m)
}

var xxx_messageInfo_Bootstrap_DynamicResources proto.InternalMessageInfo

func (m *Bootstrap_DynamicResources) GetLdsConfig() *core.ConfigSource {
	if m != nil {
		return m.LdsConfig
	}
	return nil
}

func (m *Bootstrap_DynamicResources) GetCdsConfig() *core.ConfigSource {
	if m != nil {
		return m.CdsConfig
	}
	return nil
}

func (m *Bootstrap_DynamicResources) GetAdsConfig() *core.ApiConfigSource {
	if m != nil {
		return m.AdsConfig
	}
	return nil
}

type Admin struct {
	AccessLogPath        string               `protobuf:"bytes,1,opt,name=access_log_path,json=accessLogPath,proto3" json:"access_log_path,omitempty"`
	ProfilePath          string               `protobuf:"bytes,2,opt,name=profile_path,json=profilePath,proto3" json:"profile_path,omitempty"`
	Address              *core.Address        `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	SocketOptions        []*core.SocketOption `protobuf:"bytes,4,rep,name=socket_options,json=socketOptions,proto3" json:"socket_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{1}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetAccessLogPath() string {
	if m != nil {
		return m.AccessLogPath
	}
	return ""
}

func (m *Admin) GetProfilePath() string {
	if m != nil {
		return m.ProfilePath
	}
	return ""
}

func (m *Admin) GetAddress() *core.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Admin) GetSocketOptions() []*core.SocketOption {
	if m != nil {
		return m.SocketOptions
	}
	return nil
}

type ClusterManager struct {
	LocalClusterName     string                           `protobuf:"bytes,1,opt,name=local_cluster_name,json=localClusterName,proto3" json:"local_cluster_name,omitempty"`
	OutlierDetection     *ClusterManager_OutlierDetection `protobuf:"bytes,2,opt,name=outlier_detection,json=outlierDetection,proto3" json:"outlier_detection,omitempty"`
	UpstreamBindConfig   *core.BindConfig                 `protobuf:"bytes,3,opt,name=upstream_bind_config,json=upstreamBindConfig,proto3" json:"upstream_bind_config,omitempty"`
	LoadStatsConfig      *core.ApiConfigSource            `protobuf:"bytes,4,opt,name=load_stats_config,json=loadStatsConfig,proto3" json:"load_stats_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ClusterManager) Reset()         { *m = ClusterManager{} }
func (m *ClusterManager) String() string { return proto.CompactTextString(m) }
func (*ClusterManager) ProtoMessage()    {}
func (*ClusterManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{2}
}

func (m *ClusterManager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterManager.Unmarshal(m, b)
}
func (m *ClusterManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterManager.Marshal(b, m, deterministic)
}
func (m *ClusterManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterManager.Merge(m, src)
}
func (m *ClusterManager) XXX_Size() int {
	return xxx_messageInfo_ClusterManager.Size(m)
}
func (m *ClusterManager) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterManager.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterManager proto.InternalMessageInfo

func (m *ClusterManager) GetLocalClusterName() string {
	if m != nil {
		return m.LocalClusterName
	}
	return ""
}

func (m *ClusterManager) GetOutlierDetection() *ClusterManager_OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *ClusterManager) GetUpstreamBindConfig() *core.BindConfig {
	if m != nil {
		return m.UpstreamBindConfig
	}
	return nil
}

func (m *ClusterManager) GetLoadStatsConfig() *core.ApiConfigSource {
	if m != nil {
		return m.LoadStatsConfig
	}
	return nil
}

type ClusterManager_OutlierDetection struct {
	EventLogPath         string   `protobuf:"bytes,1,opt,name=event_log_path,json=eventLogPath,proto3" json:"event_log_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterManager_OutlierDetection) Reset()         { *m = ClusterManager_OutlierDetection{} }
func (m *ClusterManager_OutlierDetection) String() string { return proto.CompactTextString(m) }
func (*ClusterManager_OutlierDetection) ProtoMessage()    {}
func (*ClusterManager_OutlierDetection) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{2, 0}
}

func (m *ClusterManager_OutlierDetection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterManager_OutlierDetection.Unmarshal(m, b)
}
func (m *ClusterManager_OutlierDetection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterManager_OutlierDetection.Marshal(b, m, deterministic)
}
func (m *ClusterManager_OutlierDetection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterManager_OutlierDetection.Merge(m, src)
}
func (m *ClusterManager_OutlierDetection) XXX_Size() int {
	return xxx_messageInfo_ClusterManager_OutlierDetection.Size(m)
}
func (m *ClusterManager_OutlierDetection) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterManager_OutlierDetection.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterManager_OutlierDetection proto.InternalMessageInfo

func (m *ClusterManager_OutlierDetection) GetEventLogPath() string {
	if m != nil {
		return m.EventLogPath
	}
	return ""
}

type Watchdog struct {
	MissTimeout          *duration.Duration `protobuf:"bytes,1,opt,name=miss_timeout,json=missTimeout,proto3" json:"miss_timeout,omitempty"`
	MegamissTimeout      *duration.Duration `protobuf:"bytes,2,opt,name=megamiss_timeout,json=megamissTimeout,proto3" json:"megamiss_timeout,omitempty"`
	KillTimeout          *duration.Duration `protobuf:"bytes,3,opt,name=kill_timeout,json=killTimeout,proto3" json:"kill_timeout,omitempty"`
	MultikillTimeout     *duration.Duration `protobuf:"bytes,4,opt,name=multikill_timeout,json=multikillTimeout,proto3" json:"multikill_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Watchdog) Reset()         { *m = Watchdog{} }
func (m *Watchdog) String() string { return proto.CompactTextString(m) }
func (*Watchdog) ProtoMessage()    {}
func (*Watchdog) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{3}
}

func (m *Watchdog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Watchdog.Unmarshal(m, b)
}
func (m *Watchdog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Watchdog.Marshal(b, m, deterministic)
}
func (m *Watchdog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Watchdog.Merge(m, src)
}
func (m *Watchdog) XXX_Size() int {
	return xxx_messageInfo_Watchdog.Size(m)
}
func (m *Watchdog) XXX_DiscardUnknown() {
	xxx_messageInfo_Watchdog.DiscardUnknown(m)
}

var xxx_messageInfo_Watchdog proto.InternalMessageInfo

func (m *Watchdog) GetMissTimeout() *duration.Duration {
	if m != nil {
		return m.MissTimeout
	}
	return nil
}

func (m *Watchdog) GetMegamissTimeout() *duration.Duration {
	if m != nil {
		return m.MegamissTimeout
	}
	return nil
}

func (m *Watchdog) GetKillTimeout() *duration.Duration {
	if m != nil {
		return m.KillTimeout
	}
	return nil
}

func (m *Watchdog) GetMultikillTimeout() *duration.Duration {
	if m != nil {
		return m.MultikillTimeout
	}
	return nil
}

type Runtime struct {
	SymlinkRoot          string          `protobuf:"bytes,1,opt,name=symlink_root,json=symlinkRoot,proto3" json:"symlink_root,omitempty"`
	Subdirectory         string          `protobuf:"bytes,2,opt,name=subdirectory,proto3" json:"subdirectory,omitempty"`
	OverrideSubdirectory string          `protobuf:"bytes,3,opt,name=override_subdirectory,json=overrideSubdirectory,proto3" json:"override_subdirectory,omitempty"`
	Base                 *_struct.Struct `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Runtime) Reset()         { *m = Runtime{} }
func (m *Runtime) String() string { return proto.CompactTextString(m) }
func (*Runtime) ProtoMessage()    {}
func (*Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{4}
}

func (m *Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runtime.Unmarshal(m, b)
}
func (m *Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runtime.Marshal(b, m, deterministic)
}
func (m *Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runtime.Merge(m, src)
}
func (m *Runtime) XXX_Size() int {
	return xxx_messageInfo_Runtime.Size(m)
}
func (m *Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_Runtime proto.InternalMessageInfo

func (m *Runtime) GetSymlinkRoot() string {
	if m != nil {
		return m.SymlinkRoot
	}
	return ""
}

func (m *Runtime) GetSubdirectory() string {
	if m != nil {
		return m.Subdirectory
	}
	return ""
}

func (m *Runtime) GetOverrideSubdirectory() string {
	if m != nil {
		return m.OverrideSubdirectory
	}
	return ""
}

func (m *Runtime) GetBase() *_struct.Struct {
	if m != nil {
		return m.Base
	}
	return nil
}

type RuntimeLayer struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to LayerSpecifier:
	//	*RuntimeLayer_StaticLayer
	//	*RuntimeLayer_DiskLayer_
	//	*RuntimeLayer_AdminLayer_
	//	*RuntimeLayer_RtdsLayer_
	LayerSpecifier       isRuntimeLayer_LayerSpecifier `protobuf_oneof:"layer_specifier"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RuntimeLayer) Reset()         { *m = RuntimeLayer{} }
func (m *RuntimeLayer) String() string { return proto.CompactTextString(m) }
func (*RuntimeLayer) ProtoMessage()    {}
func (*RuntimeLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{5}
}

func (m *RuntimeLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeLayer.Unmarshal(m, b)
}
func (m *RuntimeLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeLayer.Marshal(b, m, deterministic)
}
func (m *RuntimeLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeLayer.Merge(m, src)
}
func (m *RuntimeLayer) XXX_Size() int {
	return xxx_messageInfo_RuntimeLayer.Size(m)
}
func (m *RuntimeLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeLayer.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeLayer proto.InternalMessageInfo

func (m *RuntimeLayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isRuntimeLayer_LayerSpecifier interface {
	isRuntimeLayer_LayerSpecifier()
}

type RuntimeLayer_StaticLayer struct {
	StaticLayer *_struct.Struct `protobuf:"bytes,2,opt,name=static_layer,json=staticLayer,proto3,oneof"`
}

type RuntimeLayer_DiskLayer_ struct {
	DiskLayer *RuntimeLayer_DiskLayer `protobuf:"bytes,3,opt,name=disk_layer,json=diskLayer,proto3,oneof"`
}

type RuntimeLayer_AdminLayer_ struct {
	AdminLayer *RuntimeLayer_AdminLayer `protobuf:"bytes,4,opt,name=admin_layer,json=adminLayer,proto3,oneof"`
}

type RuntimeLayer_RtdsLayer_ struct {
	RtdsLayer *RuntimeLayer_RtdsLayer `protobuf:"bytes,5,opt,name=rtds_layer,json=rtdsLayer,proto3,oneof"`
}

func (*RuntimeLayer_StaticLayer) isRuntimeLayer_LayerSpecifier() {}

func (*RuntimeLayer_DiskLayer_) isRuntimeLayer_LayerSpecifier() {}

func (*RuntimeLayer_AdminLayer_) isRuntimeLayer_LayerSpecifier() {}

func (*RuntimeLayer_RtdsLayer_) isRuntimeLayer_LayerSpecifier() {}

func (m *RuntimeLayer) GetLayerSpecifier() isRuntimeLayer_LayerSpecifier {
	if m != nil {
		return m.LayerSpecifier
	}
	return nil
}

func (m *RuntimeLayer) GetStaticLayer() *_struct.Struct {
	if x, ok := m.GetLayerSpecifier().(*RuntimeLayer_StaticLayer); ok {
		return x.StaticLayer
	}
	return nil
}

func (m *RuntimeLayer) GetDiskLayer() *RuntimeLayer_DiskLayer {
	if x, ok := m.GetLayerSpecifier().(*RuntimeLayer_DiskLayer_); ok {
		return x.DiskLayer
	}
	return nil
}

func (m *RuntimeLayer) GetAdminLayer() *RuntimeLayer_AdminLayer {
	if x, ok := m.GetLayerSpecifier().(*RuntimeLayer_AdminLayer_); ok {
		return x.AdminLayer
	}
	return nil
}

func (m *RuntimeLayer) GetRtdsLayer() *RuntimeLayer_RtdsLayer {
	if x, ok := m.GetLayerSpecifier().(*RuntimeLayer_RtdsLayer_); ok {
		return x.RtdsLayer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RuntimeLayer) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RuntimeLayer_StaticLayer)(nil),
		(*RuntimeLayer_DiskLayer_)(nil),
		(*RuntimeLayer_AdminLayer_)(nil),
		(*RuntimeLayer_RtdsLayer_)(nil),
	}
}

type RuntimeLayer_DiskLayer struct {
	SymlinkRoot          string   `protobuf:"bytes,1,opt,name=symlink_root,json=symlinkRoot,proto3" json:"symlink_root,omitempty"`
	Subdirectory         string   `protobuf:"bytes,3,opt,name=subdirectory,proto3" json:"subdirectory,omitempty"`
	AppendServiceCluster bool     `protobuf:"varint,2,opt,name=append_service_cluster,json=appendServiceCluster,proto3" json:"append_service_cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuntimeLayer_DiskLayer) Reset()         { *m = RuntimeLayer_DiskLayer{} }
func (m *RuntimeLayer_DiskLayer) String() string { return proto.CompactTextString(m) }
func (*RuntimeLayer_DiskLayer) ProtoMessage()    {}
func (*RuntimeLayer_DiskLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{5, 0}
}

func (m *RuntimeLayer_DiskLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeLayer_DiskLayer.Unmarshal(m, b)
}
func (m *RuntimeLayer_DiskLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeLayer_DiskLayer.Marshal(b, m, deterministic)
}
func (m *RuntimeLayer_DiskLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeLayer_DiskLayer.Merge(m, src)
}
func (m *RuntimeLayer_DiskLayer) XXX_Size() int {
	return xxx_messageInfo_RuntimeLayer_DiskLayer.Size(m)
}
func (m *RuntimeLayer_DiskLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeLayer_DiskLayer.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeLayer_DiskLayer proto.InternalMessageInfo

func (m *RuntimeLayer_DiskLayer) GetSymlinkRoot() string {
	if m != nil {
		return m.SymlinkRoot
	}
	return ""
}

func (m *RuntimeLayer_DiskLayer) GetSubdirectory() string {
	if m != nil {
		return m.Subdirectory
	}
	return ""
}

func (m *RuntimeLayer_DiskLayer) GetAppendServiceCluster() bool {
	if m != nil {
		return m.AppendServiceCluster
	}
	return false
}

type RuntimeLayer_AdminLayer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuntimeLayer_AdminLayer) Reset()         { *m = RuntimeLayer_AdminLayer{} }
func (m *RuntimeLayer_AdminLayer) String() string { return proto.CompactTextString(m) }
func (*RuntimeLayer_AdminLayer) ProtoMessage()    {}
func (*RuntimeLayer_AdminLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{5, 1}
}

func (m *RuntimeLayer_AdminLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeLayer_AdminLayer.Unmarshal(m, b)
}
func (m *RuntimeLayer_AdminLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeLayer_AdminLayer.Marshal(b, m, deterministic)
}
func (m *RuntimeLayer_AdminLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeLayer_AdminLayer.Merge(m, src)
}
func (m *RuntimeLayer_AdminLayer) XXX_Size() int {
	return xxx_messageInfo_RuntimeLayer_AdminLayer.Size(m)
}
func (m *RuntimeLayer_AdminLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeLayer_AdminLayer.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeLayer_AdminLayer proto.InternalMessageInfo

type RuntimeLayer_RtdsLayer struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RtdsConfig           *core.ConfigSource `protobuf:"bytes,2,opt,name=rtds_config,json=rtdsConfig,proto3" json:"rtds_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RuntimeLayer_RtdsLayer) Reset()         { *m = RuntimeLayer_RtdsLayer{} }
func (m *RuntimeLayer_RtdsLayer) String() string { return proto.CompactTextString(m) }
func (*RuntimeLayer_RtdsLayer) ProtoMessage()    {}
func (*RuntimeLayer_RtdsLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{5, 2}
}

func (m *RuntimeLayer_RtdsLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeLayer_RtdsLayer.Unmarshal(m, b)
}
func (m *RuntimeLayer_RtdsLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeLayer_RtdsLayer.Marshal(b, m, deterministic)
}
func (m *RuntimeLayer_RtdsLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeLayer_RtdsLayer.Merge(m, src)
}
func (m *RuntimeLayer_RtdsLayer) XXX_Size() int {
	return xxx_messageInfo_RuntimeLayer_RtdsLayer.Size(m)
}
func (m *RuntimeLayer_RtdsLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeLayer_RtdsLayer.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeLayer_RtdsLayer proto.InternalMessageInfo

func (m *RuntimeLayer_RtdsLayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuntimeLayer_RtdsLayer) GetRtdsConfig() *core.ConfigSource {
	if m != nil {
		return m.RtdsConfig
	}
	return nil
}

type LayeredRuntime struct {
	Layers               []*RuntimeLayer `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LayeredRuntime) Reset()         { *m = LayeredRuntime{} }
func (m *LayeredRuntime) String() string { return proto.CompactTextString(m) }
func (*LayeredRuntime) ProtoMessage()    {}
func (*LayeredRuntime) Descriptor() ([]byte, []int) {
	return fileDescriptor_299d080550d2cf53, []int{6}
}

func (m *LayeredRuntime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayeredRuntime.Unmarshal(m, b)
}
func (m *LayeredRuntime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayeredRuntime.Marshal(b, m, deterministic)
}
func (m *LayeredRuntime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayeredRuntime.Merge(m, src)
}
func (m *LayeredRuntime) XXX_Size() int {
	return xxx_messageInfo_LayeredRuntime.Size(m)
}
func (m *LayeredRuntime) XXX_DiscardUnknown() {
	xxx_messageInfo_LayeredRuntime.DiscardUnknown(m)
}

var xxx_messageInfo_LayeredRuntime proto.InternalMessageInfo

func (m *LayeredRuntime) GetLayers() []*RuntimeLayer {
	if m != nil {
		return m.Layers
	}
	return nil
}

func init() {
	proto.RegisterType((*Bootstrap)(nil), "envoy.config.bootstrap.v3alpha.Bootstrap")
	proto.RegisterType((*Bootstrap_StaticResources)(nil), "envoy.config.bootstrap.v3alpha.Bootstrap.StaticResources")
	proto.RegisterType((*Bootstrap_DynamicResources)(nil), "envoy.config.bootstrap.v3alpha.Bootstrap.DynamicResources")
	proto.RegisterType((*Admin)(nil), "envoy.config.bootstrap.v3alpha.Admin")
	proto.RegisterType((*ClusterManager)(nil), "envoy.config.bootstrap.v3alpha.ClusterManager")
	proto.RegisterType((*ClusterManager_OutlierDetection)(nil), "envoy.config.bootstrap.v3alpha.ClusterManager.OutlierDetection")
	proto.RegisterType((*Watchdog)(nil), "envoy.config.bootstrap.v3alpha.Watchdog")
	proto.RegisterType((*Runtime)(nil), "envoy.config.bootstrap.v3alpha.Runtime")
	proto.RegisterType((*RuntimeLayer)(nil), "envoy.config.bootstrap.v3alpha.RuntimeLayer")
	proto.RegisterType((*RuntimeLayer_DiskLayer)(nil), "envoy.config.bootstrap.v3alpha.RuntimeLayer.DiskLayer")
	proto.RegisterType((*RuntimeLayer_AdminLayer)(nil), "envoy.config.bootstrap.v3alpha.RuntimeLayer.AdminLayer")
	proto.RegisterType((*RuntimeLayer_RtdsLayer)(nil), "envoy.config.bootstrap.v3alpha.RuntimeLayer.RtdsLayer")
	proto.RegisterType((*LayeredRuntime)(nil), "envoy.config.bootstrap.v3alpha.LayeredRuntime")
}

func init() {
	proto.RegisterFile("envoy/config/bootstrap/v3alpha/bootstrap.proto", fileDescriptor_299d080550d2cf53)
}

var fileDescriptor_299d080550d2cf53 = []byte{
	// 1752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4f, 0x73, 0x1b, 0xb7,
	0x15, 0x0f, 0x25, 0xca, 0x22, 0x1f, 0x69, 0x92, 0x42, 0xe4, 0x78, 0x4b, 0x27, 0x8e, 0x44, 0x3b,
	0xaa, 0xe2, 0xba, 0x64, 0x6a, 0xb9, 0x4a, 0x4c, 0x27, 0xd3, 0x84, 0x66, 0x35, 0xb6, 0xab, 0xc6,
	0x9e, 0xa5, 0x1b, 0x4f, 0x7b, 0xe8, 0x0e, 0xb4, 0x0b, 0x91, 0x18, 0x2d, 0x17, 0x3b, 0x00, 0x56,
	0x8e, 0x7a, 0xec, 0x64, 0xa6, 0xfd, 0x0c, 0xbd, 0xf4, 0xd8, 0x99, 0x4e, 0xbf, 0x43, 0xdb, 0x43,
	0xbf, 0x45, 0x2f, 0xbd, 0xf7, 0x03, 0x74, 0x7c, 0xea, 0xe0, 0xcf, 0x2e, 0xb5, 0xb4, 0x36, 0xa4,
	0x7c, 0x5b, 0x3c, 0xfc, 0xde, 0x0f, 0x0f, 0x0f, 0x3f, 0x3c, 0xbc, 0x85, 0x2e, 0x89, 0x4e, 0xd9,
	0x59, 0xcf, 0x67, 0xd1, 0x31, 0x1d, 0xf7, 0x8e, 0x18, 0x93, 0x42, 0x72, 0x1c, 0xf7, 0x4e, 0xf7,
	0x70, 0x18, 0x4f, 0xf0, 0xcc, 0xd2, 0x8d, 0x39, 0x93, 0x0c, 0xdd, 0xd4, 0xf8, 0xae, 0xc1, 0x77,
	0x67, 0xb3, 0x16, 0xdf, 0xde, 0x36, 0x7c, 0x38, 0xa6, 0x19, 0x05, 0x4e, 0xe4, 0xa4, 0xe7, 0x13,
	0x2e, 0x0d, 0x45, 0xfb, 0xc6, 0x9b, 0x10, 0x3f, 0x10, 0x76, 0xf2, 0xf6, 0x05, 0x93, 0x8c, 0x93,
	0x1e, 0x0e, 0x02, 0x4e, 0x44, 0x8a, 0xda, 0x2e, 0x40, 0x1d, 0x61, 0x41, 0x2c, 0xe4, 0x4e, 0x01,
	0xc4, 0x44, 0xee, 0x09, 0x96, 0x70, 0x9f, 0x14, 0x47, 0x14, 0x66, 0x11, 0xed, 0xe6, 0x32, 0x34,
	0x25, 0x92, 0x53, 0x5f, 0x64, 0x38, 0x21, 0xb1, 0x4c, 0x91, 0x77, 0x73, 0x48, 0x76, 0x4a, 0x78,
	0xc8, 0x70, 0x90, 0x41, 0x53, 0x83, 0x45, 0xef, 0xe4, 0xd0, 0x92, 0x63, 0x9f, 0x64, 0x50, 0x3d,
	0xca, 0x67, 0xc4, 0xe2, 0x5e, 0x61, 0x31, 0xcd, 0x60, 0x6a, 0x60, 0x51, 0x37, 0xc7, 0x8c, 0x8d,
	0x43, 0xd2, 0xd3, 0xa3, 0xa3, 0xe4, 0xb8, 0x17, 0x24, 0x1c, 0x4b, 0xca, 0x22, 0x3b, 0xff, 0xfe,
	0xfc, 0xbc, 0x90, 0x3c, 0xf1, 0x65, 0x91, 0xf7, 0x2b, 0x8e, 0xe3, 0x98, 0xf0, 0x2c, 0xdf, 0x49,
	0x10, 0xe3, 0x1e, 0x8e, 0x22, 0x26, 0x35, 0xa9, 0xe8, 0x9d, 0x12, 0x2e, 0x28, 0x8b, 0x68, 0x34,
	0xb6, 0x90, 0xeb, 0xa7, 0x38, 0xa4, 0x01, 0x96, 0xa4, 0x97, 0x7e, 0x98, 0x89, 0xce, 0x7f, 0x9a,
	0x50, 0x1d, 0xa4, 0x3a, 0x41, 0x9f, 0x40, 0x39, 0x62, 0x01, 0x71, 0x4a, 0x5b, 0xa5, 0xdd, 0xda,
	0xbd, 0xf7, 0x8d, 0xfc, 0xba, 0x38, 0xa6, 0xa9, 0x82, 0xba, 0xea, 0x94, 0xba, 0x5f, 0xb3, 0x80,
	0xb8, 0x1a, 0x89, 0x02, 0x68, 0xa9, 0x24, 0x53, 0xdf, 0xe3, 0xc4, 0x9c, 0x9a, 0x70, 0x56, 0xb4,
	0xf7, 0x83, 0xee, 0xf7, 0x8b, 0xb1, 0x9b, 0x2d, 0xdb, 0x1d, 0x69, 0x06, 0x37, 0x25, 0x70, 0x9b,
	0x22, 0x6f, 0x40, 0x63, 0xd8, 0x08, 0xce, 0x22, 0x3c, 0xcd, 0x2d, 0xb3, 0xaa, 0x97, 0xe9, 0x2f,
	0xbf, 0xcc, 0xd0, 0x50, 0xcc, 0xd6, 0x69, 0x05, 0x73, 0x16, 0xf4, 0x12, 0x9a, 0x7e, 0x98, 0x08,
	0x49, 0xb8, 0x37, 0xc5, 0x11, 0x1e, 0x13, 0xee, 0x94, 0xf5, 0x32, 0xdd, 0x45, 0xcb, 0x3c, 0x32,
	0x6e, 0xbf, 0x34, 0x5e, 0x6e, 0xc3, 0xcf, 0x8d, 0xd1, 0x01, 0xc0, 0x24, 0x10, 0x9e, 0x71, 0x77,
	0x1a, 0x9a, 0xf3, 0x87, 0x45, 0xf9, 0xfd, 0x2a, 0xa6, 0x8f, 0x34, 0x70, 0xa4, 0xc3, 0x72, 0xab,
	0x93, 0x40, 0x18, 0x03, 0xfa, 0x00, 0xe0, 0x38, 0xc4, 0x63, 0xe1, 0xc5, 0x58, 0x4e, 0x9c, 0xb5,
	0xad, 0xd2, 0x6e, 0xd5, 0xad, 0x6a, 0xcb, 0x73, 0x2c, 0x27, 0xe8, 0x31, 0xd4, 0xb4, 0xe6, 0x3d,
	0x41, 0xa3, 0x13, 0xe1, 0x5c, 0xd9, 0x5a, 0x3d, 0xb7, 0x8e, 0x8d, 0xdd, 0x5e, 0x92, 0x6c, 0x49,
	0x95, 0x7d, 0x31, 0xa2, 0xd1, 0x89, 0x0b, 0x22, 0xfd, 0x14, 0xe8, 0x10, 0xea, 0x86, 0xc9, 0x86,
	0x7c, 0x55, 0x87, 0xfc, 0xf1, 0x12, 0x54, 0x26, 0x52, 0xd7, 0x04, 0x62, 0xc3, 0xfe, 0x2d, 0x6c,
	0x1a, 0xb6, 0xe3, 0x30, 0x11, 0x13, 0x8f, 0x46, 0x92, 0xf0, 0x53, 0x1c, 0x3a, 0xeb, 0x9a, 0xf5,
	0x07, 0x5d, 0xa3, 0xf0, 0x6e, 0xaa, 0xf0, 0xee, 0xd0, 0xde, 0x8f, 0xc1, 0xc6, 0xeb, 0x41, 0xe3,
	0xaf, 0xa5, 0x5a, 0x7b, 0xb5, 0xf2, 0xb7, 0x95, 0x7b, 0xe5, 0xd6, 0x3f, 0xbe, 0xfb, 0xc2, 0x45,
	0x9a, 0xe9, 0x40, 0x11, 0x3d, 0xb1, 0x3c, 0x68, 0x08, 0x95, 0x57, 0x58, 0xfa, 0x93, 0x80, 0x8d,
	0x9d, 0x8a, 0xe6, 0xdc, 0x5d, 0x74, 0x60, 0x2f, 0x2d, 0xde, 0xcd, 0x3c, 0xd1, 0x17, 0xb0, 0xae,
	0xee, 0x36, 0x8d, 0xc6, 0x4e, 0x55, 0x93, 0xdc, 0xca, 0x93, 0x98, 0x8b, 0x9f, 0x12, 0xbc, 0x30,
	0x50, 0x37, 0xf5, 0x51, 0xe2, 0x09, 0xf1, 0x19, 0xe1, 0x24, 0xf0, 0x78, 0x12, 0x49, 0x3a, 0x25,
	0xce, 0xc6, 0x72, 0xe2, 0x39, 0x34, 0x6e, 0xae, 0xf1, 0x72, 0x1b, 0x61, 0x6e, 0x8c, 0x1e, 0xc2,
	0x1a, 0x0e, 0xa6, 0x34, 0x72, 0xea, 0x9a, 0xee, 0xa3, 0x45, 0x74, 0x5f, 0x29, 0xb0, 0x6b, 0x7c,
	0xd0, 0xaf, 0xa1, 0x95, 0xd6, 0xb6, 0x4c, 0xd3, 0xcd, 0x8b, 0xc2, 0xca, 0x2a, 0x60, 0x4a, 0xf3,
	0xcc, 0x1a, 0x52, 0x4d, 0x37, 0x59, 0xde, 0x80, 0xf6, 0xe1, 0x3a, 0x89, 0xf0, 0x51, 0x48, 0xbc,
	0x80, 0x8a, 0x58, 0x65, 0x91, 0x70, 0x4f, 0x9f, 0x8e, 0xd3, 0xda, 0x2a, 0xed, 0x56, 0xdc, 0x6b,
	0x66, 0x7a, 0x98, 0xcd, 0x6a, 0x81, 0xa0, 0x5b, 0x70, 0x75, 0x42, 0x70, 0x40, 0xb8, 0x17, 0x73,
	0x72, 0x4c, 0xbf, 0x75, 0x90, 0xd6, 0x71, 0xdd, 0x18, 0x9f, 0x6b, 0x1b, 0xf2, 0xe0, 0x03, 0x2b,
	0x65, 0xc2, 0x4f, 0x09, 0xf7, 0x6c, 0x4d, 0xf3, 0x54, 0x10, 0x9c, 0x06, 0xc4, 0x79, 0xd7, 0x16,
	0xa9, 0x79, 0xed, 0xfc, 0xea, 0x49, 0x24, 0xf7, 0xef, 0x7f, 0x83, 0xc3, 0x84, 0xb8, 0x6d, 0xa3,
	0x68, 0xcd, 0xf0, 0x8d, 0x21, 0x78, 0x66, 0xfd, 0xd1, 0x7d, 0xb8, 0x9e, 0x08, 0xe2, 0x49, 0x3f,
	0xf6, 0x8e, 0x19, 0xf7, 0x82, 0x48, 0x78, 0x21, 0x63, 0x27, 0x49, 0x2c, 0x9c, 0x4d, 0x1d, 0xfd,
	0xbb, 0x89, 0x20, 0x2f, 0xfc, 0xf8, 0x80, 0xf1, 0x61, 0x24, 0x0e, 0xcd, 0x14, 0x7a, 0x02, 0x75,
	0x55, 0xd8, 0x75, 0x54, 0xd4, 0x27, 0xce, 0x35, 0x7d, 0xc5, 0x76, 0xf2, 0xa9, 0xd4, 0xa5, 0x7f,
	0x26, 0x34, 0x31, 0x1d, 0x19, 0xb4, 0x5b, 0x7b, 0x35, 0x1b, 0xb4, 0x5f, 0x97, 0xa0, 0x39, 0x57,
	0xfa, 0xd0, 0x03, 0xa8, 0x86, 0x54, 0x48, 0x12, 0x11, 0x2e, 0x9c, 0x92, 0xe6, 0xbe, 0x71, 0x41,
	0x99, 0x38, 0xb4, 0x18, 0x77, 0x86, 0x46, 0xfb, 0x50, 0xb1, 0x45, 0x47, 0x95, 0x60, 0xe5, 0xd9,
	0xbe, 0xc0, 0xd3, 0xd6, 0x29, 0x37, 0xc3, 0xa2, 0xcf, 0x60, 0x5d, 0x10, 0x9f, 0x13, 0xa9, 0x4a,
	0xaa, 0x72, 0xbb, 0x79, 0x81, 0x9b, 0x6a, 0x13, 0xba, 0x23, 0x0d, 0x73, 0x53, 0x78, 0xbf, 0xff,
	0xa7, 0x7f, 0xfd, 0xf1, 0xe6, 0x4f, 0x61, 0xaf, 0x48, 0x8e, 0xf7, 0x8a, 0x6b, 0x7c, 0xfb, 0x2f,
	0x2b, 0xd0, 0x9a, 0x2f, 0xc8, 0xe8, 0x11, 0x40, 0x38, 0xab, 0x92, 0xe6, 0x15, 0xba, 0x5d, 0x54,
	0x25, 0xf3, 0x25, 0x32, 0xcc, 0x4a, 0xe4, 0x23, 0x00, 0x7f, 0x46, 0xb2, 0x72, 0x19, 0x12, 0x3f,
	0x23, 0x39, 0x00, 0xc0, 0x33, 0x92, 0xd5, 0x4b, 0xd6, 0x6b, 0x9c, 0xf2, 0xf4, 0x1f, 0xaa, 0x14,
	0xed, 0xc3, 0xfd, 0x65, 0x52, 0x34, 0x9f, 0x8e, 0xa7, 0xe5, 0x4a, 0xb9, 0xb5, 0xd6, 0xbf, 0xa3,
	0x28, 0x3e, 0x82, 0x5b, 0x4b, 0x50, 0x3c, 0x2d, 0x57, 0xa0, 0x55, 0x7b, 0x5a, 0xae, 0xd4, 0x5a,
	0x75, 0x77, 0xdd, 0x16, 0xa1, 0xce, 0xef, 0x57, 0x60, 0x4d, 0x97, 0x04, 0xb4, 0x03, 0x4d, 0xec,
	0xfb, 0x44, 0x28, 0xa5, 0x8f, 0xcd, 0x13, 0x52, 0xd2, 0x57, 0xef, 0xaa, 0x31, 0x1f, 0xb2, 0xb1,
	0x7e, 0x46, 0xb6, 0xa1, 0x1e, 0x73, 0x76, 0x4c, 0x43, 0x62, 0x40, 0x2b, 0x1a, 0x54, 0xb3, 0x36,
	0x0d, 0x79, 0x00, 0xeb, 0xb6, 0xeb, 0xb3, 0xd9, 0xf9, 0xb0, 0x30, 0x3b, 0x06, 0xe6, 0xa6, 0x78,
	0xf4, 0x0b, 0x68, 0x08, 0xe6, 0x9f, 0x10, 0xe9, 0xb1, 0x58, 0xf7, 0x2b, 0x4e, 0x59, 0xeb, 0xae,
	0xf0, 0x90, 0x46, 0x1a, 0xfd, 0x4c, 0x83, 0xdd, 0xab, 0xe2, 0xdc, 0x48, 0xf4, 0x77, 0x54, 0x76,
	0xb6, 0xe1, 0xc3, 0xe2, 0xec, 0xe8, 0xad, 0x77, 0xbe, 0x2b, 0x43, 0x23, 0xff, 0x46, 0xa3, 0xbb,
	0x80, 0x42, 0xe6, 0xe3, 0xd0, 0x4b, 0x9f, 0xfc, 0x08, 0x4f, 0x89, 0x4d, 0x48, 0x4b, 0xcf, 0x58,
	0x87, 0xaf, 0xf1, 0x94, 0xa0, 0x10, 0x36, 0x58, 0x22, 0x43, 0x4a, 0xb8, 0x17, 0x10, 0x49, 0x7c,
	0xb5, 0xbc, 0x55, 0xd7, 0xcf, 0x2e, 0xd7, 0x1c, 0x74, 0x9f, 0x19, 0x9e, 0x61, 0x4a, 0xe3, 0xb6,
	0xd8, 0x9c, 0x05, 0xbd, 0x80, 0xcd, 0x24, 0x16, 0x92, 0x13, 0x3c, 0xf5, 0x8e, 0x68, 0x14, 0xe4,
	0x95, 0xd8, 0x29, 0xca, 0xd4, 0x80, 0x46, 0x81, 0x7d, 0x7f, 0x51, 0xea, 0x3f, 0xb3, 0xa1, 0x11,
	0x6c, 0xe8, 0x77, 0x20, 0xf7, 0xb2, 0x97, 0x2f, 0x27, 0xee, 0xa6, 0x62, 0x38, 0xf7, 0xd0, 0xb7,
	0x7f, 0x07, 0xad, 0xf9, 0x0d, 0xa1, 0xdb, 0xd0, 0x20, 0xa7, 0x24, 0x92, 0xf3, 0x3a, 0xab, 0x6b,
	0xab, 0x95, 0x59, 0xff, 0x4b, 0x75, 0x76, 0x0f, 0xe1, 0x41, 0xf1, 0xd9, 0x2d, 0x48, 0x5c, 0xbf,
	0xa7, 0x18, 0xee, 0xc0, 0xee, 0xb2, 0x0c, 0x9d, 0xbf, 0xaf, 0x40, 0x25, 0x7d, 0xf9, 0xd1, 0xe7,
	0x50, 0x9f, 0x52, 0x21, 0x3c, 0x75, 0x4b, 0x58, 0x22, 0x6d, 0xc1, 0x29, 0xee, 0x46, 0xdc, 0x9a,
	0x82, 0xbf, 0x30, 0x68, 0x34, 0x84, 0xd6, 0x94, 0x8c, 0x71, 0x8e, 0x61, 0x65, 0x11, 0x43, 0x33,
	0x75, 0x49, 0x59, 0x3e, 0x87, 0xfa, 0x09, 0x0d, 0xc3, 0x8c, 0x61, 0x75, 0x61, 0x0c, 0x0a, 0x9e,
	0x7a, 0x1f, 0xc0, 0xc6, 0x34, 0x09, 0x25, 0xcd, 0x51, 0x94, 0x17, 0x51, 0xb4, 0x32, 0x1f, 0xcb,
	0xd3, 0xff, 0x58, 0xe5, 0xf1, 0x36, 0x74, 0x8a, 0xf3, 0x98, 0x26, 0xad, 0xf3, 0xef, 0x12, 0xac,
	0xa7, 0x8d, 0xc9, 0x36, 0xd4, 0xc5, 0xd9, 0x34, 0xa4, 0xd1, 0x89, 0xc7, 0x19, 0x93, 0xf6, 0x90,
	0x6b, 0xd6, 0xe6, 0x32, 0x26, 0x51, 0x07, 0xea, 0x22, 0x39, 0x0a, 0x28, 0x27, 0xbe, 0x64, 0xfc,
	0xcc, 0x96, 0x92, 0x9c, 0x0d, 0xed, 0xc1, 0xb5, 0xf4, 0x55, 0xf7, 0x72, 0xe0, 0x55, 0x0d, 0xde,
	0x4c, 0x27, 0x47, 0xe7, 0x9d, 0x7e, 0x04, 0x65, 0xf5, 0x43, 0x69, 0x77, 0x7b, 0xfd, 0x8d, 0xdd,
	0x8e, 0xf4, 0x2f, 0x94, 0xab, 0x41, 0xfd, 0x5d, 0xb5, 0xbf, 0x5b, 0xb0, 0x5d, 0xbc, 0x3f, 0xbb,
	0xa5, 0xce, 0x7f, 0xaf, 0x40, 0xdd, 0x7e, 0xeb, 0xae, 0x0c, 0xdd, 0x80, 0xf2, 0xac, 0x2e, 0x0c,
	0xd6, 0x5f, 0x0f, 0xca, 0x7c, 0x65, 0xab, 0xe4, 0x6a, 0xa3, 0x3a, 0x3d, 0xfb, 0xfb, 0xa3, 0x5b,
	0x36, 0x7b, 0xfe, 0x45, 0xc1, 0x3c, 0x7e, 0xc7, 0x74, 0xc5, 0xd4, 0x37, 0xd4, 0x2f, 0x01, 0x02,
	0x2a, 0x4e, 0xac, 0xaf, 0x39, 0xf9, 0xfd, 0x45, 0xb5, 0xe4, 0x7c, 0x70, 0xdd, 0x21, 0x15, 0x27,
	0xfa, 0xeb, 0xf1, 0x3b, 0x6e, 0x35, 0x48, 0x07, 0xe8, 0x37, 0x50, 0xd3, 0xcd, 0x9f, 0x65, 0x36,
	0x29, 0xfa, 0xf4, 0x52, 0xcc, 0xba, 0x6a, 0xa6, 0xd4, 0x80, 0xb3, 0x91, 0x0a, 0x9a, 0xcb, 0x40,
	0x58, 0xea, 0xb5, 0xb7, 0x08, 0xda, 0x95, 0x81, 0xc8, 0x82, 0xe6, 0xe9, 0xa0, 0xfd, 0xcf, 0x12,
	0x54, 0xb3, 0xfd, 0xbc, 0x8d, 0xb4, 0x56, 0x2f, 0x90, 0xd6, 0x7d, 0x78, 0x4f, 0xfd, 0x2b, 0x47,
	0x41, 0xda, 0xb0, 0xa5, 0xc5, 0x5e, 0x1f, 0x55, 0xc5, 0xdd, 0x34, 0xb3, 0xb6, 0x25, 0xb3, 0xc5,
	0xa2, 0xff, 0xa9, 0x92, 0xcb, 0x3d, 0xf8, 0x64, 0xa1, 0x5c, 0xe6, 0x4e, 0xa1, 0x7d, 0x00, 0x30,
	0x4b, 0x5c, 0xff, 0x33, 0x45, 0xb3, 0x07, 0x3f, 0x59, 0x92, 0x66, 0xe6, 0xd9, 0xfe, 0x73, 0x09,
	0xaa, 0x59, 0x9a, 0x10, 0x3a, 0x2f, 0x41, 0xab, 0xbc, 0x9f, 0x43, 0x4d, 0x1f, 0xc3, 0x5b, 0xb4,
	0x39, 0xfa, 0xfc, 0x6c, 0x7f, 0x72, 0xc9, 0x9d, 0x66, 0x31, 0xf5, 0x7f, 0xac, 0x1c, 0x77, 0x61,
	0x67, 0x39, 0xc7, 0xc1, 0x7b, 0xf6, 0xdf, 0xc8, 0x13, 0x31, 0xf1, 0xe9, 0x31, 0x25, 0x1c, 0xad,
	0xfe, 0x6f, 0x50, 0xea, 0xfc, 0xa1, 0x04, 0x8d, 0xfc, 0xdf, 0x0f, 0x1a, 0xc2, 0x15, 0x0d, 0x4d,
	0xfb, 0xdf, 0xbb, 0x97, 0x11, 0x97, 0x6b, 0x7d, 0x97, 0x78, 0x19, 0xf2, 0xcb, 0x0e, 0xbe, 0x84,
	0xbb, 0x94, 0x99, 0xa5, 0x62, 0xce, 0xbe, 0x3d, 0x5b, 0xb0, 0xea, 0xa0, 0x91, 0x75, 0x5d, 0xcf,
	0xd5, 0x2d, 0x7f, 0x5e, 0x3a, 0xba, 0xa2, 0xaf, 0xfb, 0xde, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xad, 0x95, 0x39, 0x10, 0xb6, 0x13, 0x00, 0x00,
}
