// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/wasm/v2/wasm.proto

package envoy_config_wasm_v2

import (
	fmt "fmt"
	core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VmConfig struct {
	VmId                 string                `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Runtime              string                `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Code                 *core.AsyncDataSource `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Configuration        string                `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	AllowPrecompiled     bool                  `protobuf:"varint,5,opt,name=allow_precompiled,json=allowPrecompiled,proto3" json:"allow_precompiled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VmConfig) Reset()         { *m = VmConfig{} }
func (m *VmConfig) String() string { return proto.CompactTextString(m) }
func (*VmConfig) ProtoMessage()    {}
func (*VmConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f222ab516220f4d, []int{0}
}

func (m *VmConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmConfig.Unmarshal(m, b)
}
func (m *VmConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmConfig.Marshal(b, m, deterministic)
}
func (m *VmConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmConfig.Merge(m, src)
}
func (m *VmConfig) XXX_Size() int {
	return xxx_messageInfo_VmConfig.Size(m)
}
func (m *VmConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VmConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VmConfig proto.InternalMessageInfo

func (m *VmConfig) GetVmId() string {
	if m != nil {
		return m.VmId
	}
	return ""
}

func (m *VmConfig) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *VmConfig) GetCode() *core.AsyncDataSource {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *VmConfig) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

func (m *VmConfig) GetAllowPrecompiled() bool {
	if m != nil {
		return m.AllowPrecompiled
	}
	return false
}

type PluginConfig struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RootId               string    `protobuf:"bytes,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	VmConfig             *VmConfig `protobuf:"bytes,3,opt,name=vm_config,json=vmConfig,proto3" json:"vm_config,omitempty"`
	Configuration        string    `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PluginConfig) Reset()         { *m = PluginConfig{} }
func (m *PluginConfig) String() string { return proto.CompactTextString(m) }
func (*PluginConfig) ProtoMessage()    {}
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f222ab516220f4d, []int{1}
}

func (m *PluginConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfig.Unmarshal(m, b)
}
func (m *PluginConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfig.Marshal(b, m, deterministic)
}
func (m *PluginConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfig.Merge(m, src)
}
func (m *PluginConfig) XXX_Size() int {
	return xxx_messageInfo_PluginConfig.Size(m)
}
func (m *PluginConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfig proto.InternalMessageInfo

func (m *PluginConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginConfig) GetRootId() string {
	if m != nil {
		return m.RootId
	}
	return ""
}

func (m *PluginConfig) GetVmConfig() *VmConfig {
	if m != nil {
		return m.VmConfig
	}
	return nil
}

func (m *PluginConfig) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

type WasmService struct {
	Config               *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Singleton            bool          `protobuf:"varint,2,opt,name=singleton,proto3" json:"singleton,omitempty"`
	StatPrefix           string        `protobuf:"bytes,3,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WasmService) Reset()         { *m = WasmService{} }
func (m *WasmService) String() string { return proto.CompactTextString(m) }
func (*WasmService) ProtoMessage()    {}
func (*WasmService) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f222ab516220f4d, []int{2}
}

func (m *WasmService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmService.Unmarshal(m, b)
}
func (m *WasmService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmService.Marshal(b, m, deterministic)
}
func (m *WasmService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmService.Merge(m, src)
}
func (m *WasmService) XXX_Size() int {
	return xxx_messageInfo_WasmService.Size(m)
}
func (m *WasmService) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmService.DiscardUnknown(m)
}

var xxx_messageInfo_WasmService proto.InternalMessageInfo

func (m *WasmService) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *WasmService) GetSingleton() bool {
	if m != nil {
		return m.Singleton
	}
	return false
}

func (m *WasmService) GetStatPrefix() string {
	if m != nil {
		return m.StatPrefix
	}
	return ""
}

func init() {
	proto.RegisterType((*VmConfig)(nil), "envoy.config.wasm.v2.VmConfig")
	proto.RegisterType((*PluginConfig)(nil), "envoy.config.wasm.v2.PluginConfig")
	proto.RegisterType((*WasmService)(nil), "envoy.config.wasm.v2.WasmService")
}

func init() { proto.RegisterFile("envoy/config/wasm/v2/wasm.proto", fileDescriptor_6f222ab516220f4d) }

var fileDescriptor_6f222ab516220f4d = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x8b, 0xd4, 0x30,
	0x14, 0xc7, 0x89, 0x76, 0x67, 0xdb, 0x37, 0x0a, 0x1a, 0x85, 0x2d, 0xcb, 0xe2, 0x0e, 0xc5, 0xc3,
	0x80, 0x90, 0x62, 0x05, 0x0f, 0x7a, 0x72, 0xf5, 0xb2, 0xb7, 0xd2, 0x01, 0x3d, 0x0e, 0x99, 0x36,
	0x33, 0x04, 0x9a, 0xa4, 0xa4, 0x69, 0x66, 0xe6, 0x1b, 0xf8, 0x29, 0xfc, 0x34, 0x7e, 0x30, 0x49,
	0xd2, 0x32, 0x8e, 0xcc, 0xc1, 0x53, 0x9b, 0xff, 0x7b, 0x2f, 0xff, 0xf7, 0xfb, 0x13, 0xb8, 0x67,
	0xd2, 0xaa, 0x63, 0x5e, 0x2b, 0xb9, 0xe5, 0xbb, 0x7c, 0x4f, 0x7b, 0x91, 0xdb, 0xc2, 0x7f, 0x49,
	0xa7, 0x95, 0x51, 0xf8, 0xb5, 0x6f, 0x20, 0xa1, 0x81, 0xf8, 0x82, 0x2d, 0x6e, 0xef, 0xc2, 0x18,
	0xed, 0xb8, 0x6b, 0xaf, 0x95, 0x66, 0xf9, 0x86, 0xf6, 0x2c, 0xcc, 0xdc, 0xde, 0x58, 0xda, 0xf2,
	0x86, 0x1a, 0x96, 0x4f, 0x3f, 0xa1, 0x90, 0xfd, 0x46, 0x10, 0x7f, 0x17, 0x5f, 0xfd, 0x5d, 0xf8,
	0x15, 0x5c, 0x59, 0xb1, 0xe6, 0x4d, 0x8a, 0x16, 0x68, 0x99, 0x54, 0x91, 0x15, 0x8f, 0x0d, 0x4e,
	0xe1, 0x5a, 0x0f, 0xd2, 0x70, 0xc1, 0xd2, 0x27, 0x5e, 0x9e, 0x8e, 0xf8, 0x23, 0x44, 0xb5, 0x6a,
	0x58, 0xfa, 0x74, 0x81, 0x96, 0xf3, 0x22, 0x23, 0x61, 0x2f, 0xda, 0x71, 0x62, 0x0b, 0xe2, 0x36,
	0x20, 0x5f, 0xfa, 0xa3, 0xac, 0xbf, 0x51, 0x43, 0x57, 0x6a, 0xd0, 0x35, 0xab, 0x7c, 0x3f, 0x7e,
	0x0b, 0xcf, 0xc3, 0xf2, 0x83, 0xa6, 0x86, 0x2b, 0x99, 0x46, 0xfe, 0xde, 0x73, 0x11, 0xbf, 0x83,
	0x97, 0xb4, 0x6d, 0xd5, 0x7e, 0xdd, 0x69, 0x56, 0x2b, 0xd1, 0xf1, 0x96, 0x35, 0xe9, 0xd5, 0x02,
	0x2d, 0xe3, 0xea, 0x85, 0x2f, 0x94, 0x27, 0x3d, 0xfb, 0x85, 0xe0, 0x59, 0xd9, 0x0e, 0x3b, 0x2e,
	0x47, 0x14, 0x0c, 0x91, 0xa4, 0x82, 0x4d, 0x24, 0xee, 0x1f, 0xdf, 0xc0, 0xb5, 0x56, 0xca, 0x38,
	0xc0, 0x40, 0x32, 0x73, 0xc7, 0xc7, 0x06, 0x7f, 0x86, 0xc4, 0x8a, 0x75, 0xb0, 0x1f, 0x69, 0xde,
	0x90, 0x4b, 0x29, 0x93, 0x29, 0xaa, 0x2a, 0xb6, 0x53, 0x68, 0xff, 0x45, 0x93, 0xfd, 0x44, 0x30,
	0xff, 0x41, 0x7b, 0xb1, 0x62, 0xda, 0xf2, 0x9a, 0xe1, 0x4f, 0x30, 0x1b, 0xfd, 0xd0, 0x59, 0x7a,
	0xff, 0xf8, 0xfd, 0xcd, 0x54, 0x8d, 0x13, 0xf8, 0x0e, 0x92, 0x9e, 0xcb, 0x5d, 0xcb, 0x8c, 0x92,
	0x9e, 0x24, 0xae, 0x4e, 0x02, 0xbe, 0x87, 0x79, 0x6f, 0xa8, 0x71, 0xb1, 0x6d, 0xf9, 0xc1, 0xe3,
	0x24, 0x15, 0x38, 0xa9, 0xf4, 0xca, 0xc3, 0x7b, 0xc8, 0xb8, 0x0a, 0x76, 0x9d, 0x56, 0x87, 0xe3,
	0x45, 0xe7, 0x87, 0xc4, 0x6d, 0x5b, 0xba, 0x37, 0x52, 0xa2, 0xcd, 0xcc, 0x3f, 0x96, 0x0f, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xf4, 0x1f, 0x47, 0x9c, 0x02, 0x00, 0x00,
}
